### ISSUE TITLE
Can we change default values?

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/sc-plugin-vmware-vsphere-45#2] opened 2022-04-13 14:24 UTC
Page: [Download job logs](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere-45/scpivs44_download_job_logs.html)

The note at the top of the page says:
The default value for retaining job logs is 30 days; the default value for retaining jobs is 90 days. 

If it's default it should be able to be changed.  Can you link to the instructions on how to change it?  And if the instructions don't exist can  they be created and then linked to?

(I couldn't find the instructions, so I don't know that they exist.)

**Comment by ntap-bmegan** [comment] 2022-09-23 14:05
@netapp-soumikd, @netapp-chandaj - Please update status or close if work is complete.

**Comment by netapp-soumikd** [comment] 2022-09-26 05:06
@netapp-jani Please verify if this issue is fixed and update accordingly.

**Comment by netapp-jani** [comment] 2022-09-27 06:46
The issue is fixed in SnapCenter Plug-in for VMware vSphere 4.7. Link to the page: [Download job logs](https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_download_job_logs.html)

**Closed by netapp-jani** 2022-09-27 06:46 UTC
Labels: documentation

**Comment by Ronya-Robinson** [comment] 2022-10-11 07:48
Use the Configuration REST APIs for SnapCenter Plug-in for VMware vSphere to change the default values for retaining job logs and retaining jobs.
Link to the SCV Swagger:
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_access_rest_apis_using_the_swagger_api_web_page.html

***@***.***

Use these APIs to manage any configuration parameter. Use the GET API to see the current value and use the PUT API to modify the value.

Configuration Name
Configuration Value
Description
JobLogRetentionDays
30 (Default)
retaining job logs
JobRetentionDays
90 (Default)
retaining jobs

Ronya Robinson
Information Engineering
